### ISSUE TITLE
Is Python 2.7 supported?

### ISSUE THREAD

**Issue by dbapl** [leforestier/naval#1]
```
    from naval.core import *
exceptions.SyntaxError: invalid syntax (core.py, line 317)
```
The line is:
`def __init__(self, *lists, unexpected_keys = FAIL):`

This will not work in 2.7. It will have to be:
`def __init__(self, *lists, **kwargs):`

What versions of Python are supported?

**Comment by leforestier** [comment]
You're right, I had tested the library only with Python 3.
It seems there's more than just this issue to fix in order to adapt the library for Python 2 so I'll look into it tomorrow.

**Comment by leforestier** [comment]
I modified the library so that it works with Python 2.7.

The library now requires postpone>=0.2.0 to deal with the different types of strings in Python 2.

If you're going to use Naval with Python 2, I recommend you use `unicode` strings when defining custom error messages, since the default error messages in Naval in Python 2 have the `unicode` type.

I uploaded the new version of Naval on Pypi so it is now possible to `pip install` it.
